import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="container flex items-center justify-between py-4 mx-auto">
          <a href="">Home</a>
          <ul className="flex items-center justify-between gap-10">
            <li className="">Contact</li>
            <li>About</li>
          </ul>
        </nav>
        {children}
        <footer>Hello World</footer>
      </body>
    </html>
  );
}
